    # =========================
    # PORT LISTEN
    # =========================
   # Nginx port 80 (HTTP) pe request sun raha hai
server {
    listen 80;
    server_name localhost;

    # =========================
    # FRONTEND SETUP (React build files)
    # =========================
    root /usr/share/nginx/html;
     # React/Vite build files yahan serve hoti hain
         # Default file jo load hogi
    index index.html;


# =========================
    # REACT ROUTING FIX (IMPORTANT)
    # =========================
        # Agar file na mile to index.html load karo
        # React Router ke liye zaroori hai (SPA fix)
    location / {
        try_files $uri $uri/ /index.html;
    }
# =========================
    # BACKEND API PROXY
    # =========================
    location /api {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}




